# Generated by Django 5.2.3 on 2025-07-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='user',
        ),
    ]
