# Generated by Django 5.2.3 on 2025-07-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ubicacionrepartidor'),
        ('api', '0004_alter_pedido_estado'),
    ]

    operations = [
    ]
