# Generated by Django 5.2.3 on 2025-07-24 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pedido_cliente_email_pedido_cliente_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Casa, Trabajo, Universidad', max_length=100)),
                ('direccion', models.TextField(help_text='Dirección completa')),
                ('referencia', models.TextField(blank=True, help_text='Referencia o punto de referencia', null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de Usuario',
                'verbose_name_plural': 'Direcciones de Usuarios',
                'ordering': ['-actualizada_en'],
            },
        ),
    ]
