# Generated by Django 5.2.3 on 2025-07-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
